version: "3.8"
services:
  db: 
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=matryxforsnipetechstandalone
      - MYSQL_USER=matryx_docker
      - MYSQL_PASSWORD=PogiAko2023 # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
    ports:
    - 3306:3306
  www:
    build: .
    restart: always
    image: php:apache
    volumes:
      - "/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 8888:80
      - 443:443 # for future ssl traffic
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

#sudo docker-php-ext-install pdo_mysql
#sudo docker-php-ext-enable pdo_mysql